apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: hospitaline-db
  namespace: hospitaline-prod
spec:
  serviceAccountName: hospitaline-api
  secretProviderClassName: hospitaline-db-secrets
  secretObject:
    type: Opaque
    data:
      - sourcePath: "DB_USER"
        targetKey: "DB_USER"
      - sourcePath: "DB_PASSWORD"
        targetKey: "DB_PASSWORD"
      - sourcePath: "DB_NAME"
        targetKey: "DB_NAME"