apiVersion: v1
kind: ServiceAccount
metadata:
  name: hospitaline-api
  namespace: hospitaline-prod
  annotations:
    iam.gke.io/gcp-service-account: hospitaline-gke@project-39d0c894-3885-4211-89d.iam.gserviceaccount.com