apiVersion: v1
kind: Service
metadata:
  name: hospitaline-api
  namespace: hospitaline-prod
spec:
  selector:
    app: hospitaline-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP